export const projects_list = [
  {
    id: 9,
    title: 'Employees CRUD',
    category: 'react',
    img: './img/projects/employees_crud.png',
    github_url: 'https://github.com/dupudev/react-employees-crud',
    url: 'https://dupudev.github.io/react-employees-crud/',
  },
  {
    id: 8,
    title: 'Fitness Trainer',
    category: 'static',
    img: './img/projects/fitness_trainer.png',
    github_url:
      'https://github.com/dupudev/static-06-fitness-trainer-html-sass-js',
    url: 'https://dupudev.github.io/static-06-fitness-trainer-html-sass-js/',
  },
  {
    id: 7,
    title: 'Weather App',
    category: 'react',
    img: './img/projects/weather_app.png',
    github_url: 'https://github.com/dupudev/react-weather-app',
    url: 'https://dupudev.github.io/react-weather-app/',
  },
  {
    id: 6,
    title: 'Fake Store',
    category: 'react',
    img: './img/projects/fake_store.png',
    github_url: 'https://github.com/dupudev/react-simple-web-shop',
    url: 'https://dupudev.github.io/react-simple-web-shop/',
  },
  {
    id: 5,
    title: 'Password Generator',
    category: 'react',
    img: './img/projects/password_generator.png',
    github_url: 'https://github.com/dupudev/react-password-generator',
    url: 'https://dupudev.github.io/react-password-generator/',
  },
  {
    id: 4,
    title: 'The Moon',
    category: 'static',
    img: './img/projects/moon.png',
    github_url: 'https://github.com/dupudev/static-05-moon-html-scss-js',
    url: 'https://dupudev.github.io/static-05-moon-html-scss-js/',
  },
  {
    id: 3,
    title: 'Spatial',
    category: 'static',
    img: './img/projects/spatial.png',
    github_url: 'https://github.com/dupudev/static-02-spatial-html-css',
    url: 'https://dupudev.github.io/static-02-spatial-html-css/',
  },
  {
    id: 2,
    title: 'Basic CRUD',
    category: 'react',
    img: './img/projects/basic_crud.png',
    github_url: 'https://github.com/dupudev/react-basic-crud',
    url: 'https://dupudev.github.io/react-basic-crud/',
  },
  {
    id: 1,
    title: 'Shopping List',
    category: 'react',
    img: './img/projects/shopping_list.png',
    github_url: 'https://github.com/dupudev/react-shopping-list',
    url: 'https://dupudev.github.io/react-shopping-list/',
  },
];
